# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='evaluation',
            field=models.CharField(max_length=255),
        ),
    ]
