# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20170519_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
