# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('Asian', 'Asian'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Spanish', 'Spanish'), ('American', 'American'), ('French', 'French'), ('Italian', 'Italian')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='goal',
            field=models.CharField(blank=True, choices=[('Earn money', 'Earn money'), ('Meet new friends', 'Meet new friends'), ('Personal interests', 'Personal interests')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='chef_experience',
            field=models.CharField(blank=True, choices=[('Newbie', 'Newbie'), ('Self-taught', 'Self-taught'), ('Professional', 'Professional'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='chef_type',
            field=models.CharField(blank=True, choices=[('Not sure', 'Not sure'), ('Not sure', 'Not sure'), ('Not sure', 'Not sure')], max_length=20, null=True),
        ),
    ]
