# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20170523_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='seller',
        ),
    ]
