# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Where are you from?'),
        ),
    ]
