# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoyo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
