# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_users',
            field=models.ManyToManyField(null=True, related_name='_user_saved_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
