# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phoyo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoyo',
            new_name='photo',
        ),
    ]
