# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_saved_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./user_pic', verbose_name='Photo of User'),
        ),
    ]
