# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170522_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.CharField(blank=True, max_length=255, verbose_name='Where are you from?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='./user_bac', verbose_name='Profile background'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Where do you currently live?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./user_pic', verbose_name='Profile photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Profile introduction'),
        ),
    ]
