# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170522_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='./user_bac', verbose_name='Background of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./user_pic', verbose_name='Photo of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Brief Introduction'),
        ),
    ]
