# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='./user_bac', verbose_name='Background of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
