# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170522_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longtitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
