# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_saved_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='saved_users',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
