# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170607_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, default='00', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='longtitude',
            field=models.CharField(blank=True, default='00', max_length=100),
        ),
    ]
