# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170516_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_description',
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=55, verbose_name='Name of User'),
        ),
    ]
