# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170608_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geohash',
            field=models.CharField(blank=True, default='###', max_length=20),
        ),
    ]
