# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170516_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brief Introduction of User'),
        ),
    ]
