# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170516_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='introduction',
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
