# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170617_2116'),
        ('users', '0006_user_geohash'),
    ]

    operations = [
    ]
