# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170514_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./user_pic', verbose_name='Picture of User'),
        ),
    ]
