# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import riceshare.users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170514_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=riceshare.users.storage.ImageStorage(), upload_to='./user_pic', verbose_name='Picture of User'),
        ),
    ]
